import { NextRequest, NextResponse } from "next/server";
import { getImageProvider } from "@/lib/image-providers";
import { persistGeneratedImage } from "@/lib/image-persist";
import { prisma } from "@/lib/db";
import { buildPlanBriefFromDetailAsset } from "@/app/ai-image/v2/domain/plan-brief";
import { buildPromptFromBrief } from "../../plan/lib/brief-prompt-builder";

type DetailType = "detail" | "multi_angle" | "lifestyle" | "feature";

function buildDetailPrompt(args: {
  type: DetailType;
  productDescription: string;
}): string {
  const brief = buildPlanBriefFromDetailAsset(args.type, args.productDescription);
  if (brief) {
    return buildPromptFromBrief(
      { ...brief, styleStrategy: { ...brief.styleStrategy, count: 1 } },
      { userInput: args.productDescription, mode: "image" }
    );
  }

  // Graceful fallback: legacy hardcoded prompt
  const base = (args.productDescription || "").trim();
  const product = base ? `Product: ${base}\n` : "";
  const common = [
    "You are generating an e-commerce product image.",
    "Keep the product identity consistent with the reference image.",
    "Maintain the same overall style as the style reference image, but vary composition and emphasis.",
    "No text, no typography, no logos, no watermarks.",
    "Clean commercial look, realistic materials and lighting.",
  ].join("\n");

  const perType: Record<DetailType, string> = {
    detail: [
      "Focus: close-up detail shot that highlights craftsmanship, texture, edges, and key functional surfaces.",
      "Composition: macro / near-macro, shallow depth of field allowed, product remains recognizable.",
    ].join("\n"),
    multi_angle: [
      "Focus: a different angle of the same product (rotate viewpoint), showing overall form and structure.",
      "Composition: three-quarter view, clean background, consistent lighting and color mood.",
    ].join("\n"),
    lifestyle: [
      "Focus: realistic usage or contextual scene that matches the product category, still commercial and clean.",
      "Composition: product remains the hero; background elements unbranded and minimal.",
    ].join("\n"),
    feature: [
      "Focus: highlight one selling point through composition (e.g., durability, sharpness, coating, precision).",
      "Composition: hero product with supporting props only if needed; keep it believable.",
    ].join("\n"),
  };

  return `${common}\n\n${product}\n${perType[args.type]}`.trim();
}

function resolveUrl(origin: string, maybeUrl: unknown): string | null {
  if (typeof maybeUrl !== "string") return null;
  const u = maybeUrl.trim();
  if (!u) return null;
  if (u.startsWith("/")) return `${origin}${u}`;
  return u;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      heroImageUrl,
      productDescription,
      selectedTypes,
      output,
    } = body as {
      heroImageUrl?: unknown;
      productDescription?: unknown;
      selectedTypes?: unknown;
      output?: { width?: unknown; height?: unknown };
    };

    const origin = request.nextUrl?.origin || process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
    const resolvedHeroImageUrl = resolveUrl(origin, heroImageUrl);
    if (!resolvedHeroImageUrl) {
      return NextResponse.json({ error: "缺少主图 heroImageUrl" }, { status: 400 });
    }

    const types: DetailType[] = Array.isArray(selectedTypes)
      ? (selectedTypes.filter((t): t is DetailType =>
          t === "detail" || t === "multi_angle" || t === "lifestyle" || t === "feature"
        ) as DetailType[])
      : [];
    if (types.length === 0) {
      return NextResponse.json({ error: "selectedTypes 不能为空" }, { status: 400 });
    }

    const width = Number.isFinite(Number(output?.width)) ? Number(output?.width) : 1920;
    const height = Number.isFinite(Number(output?.height)) ? Number(output?.height) : 1920;

    const providerName = body.provider || process.env.IMAGE_PROVIDER || "pollinations";
    const provider = getImageProvider(providerName);

    const pages: Array<{ type: DetailType; imageUrl: string; taskId?: string }> = [];
    let index = 0;
    for (const type of types) {
      const prompt = buildDetailPrompt({
        type,
        productDescription: typeof productDescription === "string" ? productDescription : "",
      });

      // Create task record before generation for tracking
      const task = await prisma.aiImageTask.create({
        data: {
          tenantId: "default",
          userId: "default",
          promptSnapshot: prompt,
          userPrompt: typeof productDescription === "string" ? productDescription.trim() : null,
          negativePromptSnapshot:
            "text, typography, letters, words, numbers, watermark, ai generated mark, logo, signature, corner badge, copyright stamp, generated by, ai watermark, brand mark, label, stamp, qr code",
          configSnapshot: JSON.stringify({ width, height, detailType: type, strictSize: true, model: "default", quality: "standard" }),
          referenceImagesSnapshot: JSON.stringify({ productImageUrl: resolvedHeroImageUrl, styleReferenceUrls: [resolvedHeroImageUrl] }),
          status: "processing",
          provider: providerName,
        },
      });

      const result = await provider.generate({
        prompt,
        negativePrompt:
          "text, typography, letters, words, numbers, watermark, ai generated mark, logo, signature, corner badge, copyright stamp, generated by, ai watermark, brand mark, label, stamp, qr code",
        productImageUrl: resolvedHeroImageUrl,
        styleReferenceUrls: [resolvedHeroImageUrl],
        width,
        height,
        strictSize: true,
        model: "default",
        quality: "standard",
      });

      if (!result.success || !result.imageUrl) {
        await prisma.aiImageTask.update({
          where: { id: task.id },
          data: { status: "failed", errorMessage: result.error || "生成失败" },
        });
        return NextResponse.json({ error: result.error || "生成失败" }, { status: 500 });
      }

      // Persist image locally so URLs survive page refreshes
      const fileName = `detail-${Date.now()}-${index}.png`;
      const localUrl = await persistGeneratedImage(result.imageUrl, fileName, origin);
      const effectiveUrl = localUrl || result.imageUrl;

      await prisma.aiImageTask.update({
        where: { id: task.id },
        data: {
          status: "completed",
          resultImageUrl: JSON.stringify([effectiveUrl]),
        },
      });

      pages.push({ type, imageUrl: effectiveUrl, taskId: task.id });
      index++;
    }

    return NextResponse.json({ pages });
  } catch (error) {
    console.error("[v2/detail/generate] Failed:", error);
    return NextResponse.json({ error: "生成失败" }, { status: 500 });
  }
}
