import { NextRequest, NextResponse } from "next/server";
import { getImageProvider } from "@/lib/image-providers";
import { persistGeneratedImage } from "@/lib/image-persist";
import { prisma } from "@/lib/db";
import { getAuthScope, requireActiveAuthorizationCode, scopedTenantUserWhere } from "@/lib/auth-scope";
import { checkAndResetQuotaForScope, deductQuotaForScope, quotaErrorMessage } from "@/lib/quota";
import type { CreativePlan } from "@/app/ai-image/v2/types";

type DetailType = "detail" | "multi_angle" | "lifestyle" | "feature" | "comparison" | "spec";

function detailTypeDefaultsToMarketingCopy(): boolean {
  return true;
}

interface HeroPlanContext {
  headline?: string;
  subtitle?: string;
  sellingPoints?: string[];
  visualDirection?: string;
  colorDirection?: string;
  layoutDirection?: string;
  productName?: string;
  productAnalysis?: {
    productType?: string;
    productSubjectDescription?: string;
    visibleFeatures?: string[];
    materialGuess?: string;
    structureRisks?: string[];
  };
  copyBlocks?: Array<{ title?: string; body?: string; role?: string }>;
}

const LLM_API_URL = process.env.LLM_API_URL || `${process.env.NEXT_PUBLIC_CHATGPT2API_URL || "http://localhost:3000/v1"}/chat/completions`;
const LLM_MODEL = process.env.LLM_MODEL || "auto";
const LLM_AUTH_KEY = process.env.VOLCANO_API_KEY || process.env.KIMI_API_KEY || process.env.NEXT_PUBLIC_CHATGPT2API_KEY || "chatgpt2api";

function hasExplicitProductGeometryChangeIntent(text?: string): boolean {
  if (!text) return false;
  const normalized = text.toLowerCase();
  const patterns = [
    /(修改|调整|改变|变更|更改|改一下).{0,8}(产品|商品|主体)?(尺寸|大小|比例|长短|长度|宽度|高度|直径|数量|个数)/,
    /(产品|商品|主体).{0,8}(放大|缩小|变大|变小|加大|减小|拉长|压扁|变宽|变窄)/,
    /(放大|缩小|变大|变小|加大|减小|拉长|压扁|变宽|变窄).{0,8}(产品|商品|主体|尺寸|大小|比例)/,
    /(增加|添加|加上|多放|多加|减少|删掉|删除|去掉).{0,8}(产品|商品|主体|数量|个|件)/,
    /(改成|变成|换成|做成|生成).{0,8}\d+\s*(个|件|只|根|支|套|pcs?|pieces?)/,
    /(只要|仅保留|保留).{0,8}\d+\s*(个|件|只|根|支|套|pcs?|pieces?)/,
    /(多个|多件).{0,8}(产品|商品|主体|变体|规格|个|件)/,
    /(尺寸系列|不同尺寸|不同规格)/,
    /(产品|商品|主体|变体|规格).{0,8}(多个|多件|套装|组合|系列|尺寸系列|不同尺寸|不同规格)/,
    /\b(make|turn|change|convert)\b.{0,40}\b(into|to)\b.{0,20}\d+\s*(pcs?|pieces?|items?|units?)\b/,
    /\b(change|modify|adjust|resize|rescale|scale up|scale down|make larger|make smaller)\b.{0,40}\b(product|item|object|size|dimension|scale|proportion|quantity|count)\b/,
    /\b(add|remove|delete|duplicate|multiple|several|set of|lineup|quantity|count)\b.{0,40}\b(product|item|object|variant|pieces?)\b/,
  ];
  return patterns.some((pattern) => pattern.test(normalized));
}

function hasExplicitExactTextKeepIntent(text?: string): boolean {
  if (!text) return false;
  const normalized = text.toLowerCase();
  const patterns = [
    /(保持|保留|不要改|别改).{0,8}(原文字|原文案|原标题|文字不变|文案不变|标题不变)/,
    /(文字|文案|标题|字幕|标语).{0,8}(保持不变|不要改|别改|原样保留)/,
    /\b(keep|preserve)\b.{0,24}\b(original|existing|same)\b.{0,16}\b(text|copy|headline|title|typography)\b/,
    /\b(do not|don't)\b.{0,16}\b(change|modify|rewrite)\b.{0,16}\b(text|copy|headline|title)\b/,
  ];
  return patterns.some((pattern) => pattern.test(normalized));
}

function hasExplicitTextRemovalIntent(text?: string): boolean {
  if (!text) return false;
  const normalized = text.toLowerCase();
  const patterns = [
    /(不要|去掉|删除|移除|隐藏|取消).{0,8}(文字|文案|标题|字幕|标语|标签)/,
    /(无文字|无文案|不要标题|不要字幕|不要任何文字|纯图|无字图)/,
    /\b(no text|without text|remove text|remove headline|no headline|no typography|textless)\b/,
  ];
  return patterns.some((pattern) => pattern.test(normalized));
}

function buildDetailNegativePrompt(
  type: DetailType,
  productLevelChangeAllowed: boolean,
  includeMarketingCopy: boolean
): string {
  const base =
    "watermark, ai generated mark, logo, signature, corner badge, copyright stamp, generated by, ai watermark, brand mark, label as decoration, stamp, qr code";
  const geometry =
    "wrong product identity, deformed product, missing holes, extra holes, missing threads, wrong thread pitch, altered contours, invented parts";
  const copyLock = !includeMarketingCopy
    ? ", heavy marketing headline, dense text cards, fake product label, unreadable text, garbled typography"
    : "";

  if (productLevelChangeAllowed) {
    return `${base}, ${geometry}${copyLock}`;
  }

  if (type === "detail") {
    const detailLock =
      "fake macro detail, invented close-up structure, unrelated object texture, wrong material close-up, altered holes, altered edges, altered threads";
    return `${base}, ${detailLock}, ${geometry}${copyLock}`;
  }

  const scaleLock =
    "changed product size, changed product scale, wrong dimensions, resized product body, size progression, varying product lengths, inconsistent item sizes";
  if (type === "comparison") {
    return `${base}, ${scaleLock}, duplicate featured product, mutated featured product, missing featured product, ${geometry}${copyLock}`;
  }

  const countLock =
    "extra product, duplicate product, multiple product copies, missing product, removed product, added variants, bundle lineup, extra bit in use, extra tool bit";
  const lifestyleLock =
    type === "lifestyle"
      ? ", unchanged original background, studio-only product shot, generic blank backdrop, background duplicate of featured product, copied product part in use, missing kit component"
      : "";
  return `${base}, ${scaleLock}, ${countLock}${lifestyleLock}, ${geometry}${copyLock}`;
}

function extractHeroContext(plan?: CreativePlan | null): HeroPlanContext | null {
  if (!plan) return null;
  return {
    headline: plan.headline || undefined,
    subtitle: plan.subtitle || undefined,
    sellingPoints: plan.sellingPoints || undefined,
    visualDirection: plan.visualDirection || undefined,
    colorDirection: plan.colorDirection || undefined,
    layoutDirection: plan.layoutDirection || undefined,
    productName: plan.productName || undefined,
    productAnalysis: plan.productAnalysis
      ? {
          productType: plan.productAnalysis.productType || undefined,
          productSubjectDescription: plan.productAnalysis.productSubjectDescription || undefined,
          visibleFeatures: plan.productAnalysis.visibleFeatures || undefined,
          materialGuess: plan.productAnalysis.materialGuess || undefined,
          structureRisks: plan.productAnalysis.structureRisks || undefined,
        }
      : undefined,
    copyBlocks:
      plan.copyBlocks
        ?.filter((b) => b.role === "headline" || b.role === "core_claim" || b.role === "feature_point")
        .slice(0, 3)
        .map((b) => ({ title: b.title, body: b.body, role: b.role })) || undefined,
  };
}

function buildDetailPrompt(args: {
  type: DetailType;
  productDescription: string;
  heroContext?: HeroPlanContext | null;
  referenceImageCount?: number;
  activeReferenceIndex?: number;
  allowProductGeometryChange?: boolean;
  includeMarketingCopy?: boolean;
  preserveExactText?: boolean;
}): string {
  const base = (args.productDescription || "").trim();
  const hero = args.heroContext;
  const allowProductGeometryChange = args.allowProductGeometryChange === true;
  const includeMarketingCopy = args.includeMarketingCopy !== false;
  const preserveExactText = args.preserveExactText === true;
  const isComparison = args.type === "comparison";
  const typeAllowsMarketingCopy = detailTypeDefaultsToMarketingCopy();
  const effectiveIncludeMarketingCopy = includeMarketingCopy && (preserveExactText || typeAllowsMarketingCopy);
  const shouldUseHeroCopyDirection = effectiveIncludeMarketingCopy;

  // Build product and copy-direction context from heroPlan analysis + user description.
  // heroPlan text guides the detail slide; it is not mandatory output copy.
  const productLines: string[] = [];
  if (hero?.productName) productLines.push(`Product Name: ${hero.productName}`);
  if (hero?.productAnalysis?.productType) productLines.push(`Category: ${hero.productAnalysis.productType}`);
  if (hero?.productAnalysis?.productSubjectDescription) productLines.push(`Description: ${hero.productAnalysis.productSubjectDescription}`);
  if (hero?.productAnalysis?.visibleFeatures && hero.productAnalysis.visibleFeatures.length > 0)
    productLines.push(`Visible Features: ${hero.productAnalysis.visibleFeatures.join("; ")}`);
  if (hero?.productAnalysis?.materialGuess) productLines.push(`Material: ${hero.productAnalysis.materialGuess}`);
  if (hero?.productAnalysis?.structureRisks && hero.productAnalysis.structureRisks.length > 0)
    productLines.push(`Structure Notes: ${hero.productAnalysis.structureRisks.join("; ")}`);
  if (shouldUseHeroCopyDirection && hero?.sellingPoints && hero.sellingPoints.length > 0)
    productLines.push(`Key Selling Points: ${hero.sellingPoints.join(" | ")}`);
  if (shouldUseHeroCopyDirection && hero?.copyBlocks && hero.copyBlocks.length > 0) {
    const msgs = hero.copyBlocks
      .filter((b) => b.title || b.body)
      .map((b) => (b.body ? `${b.title}: ${b.body}` : b.title))
      .join(" | ");
    if (msgs) productLines.push(`Copy Direction Reference (not mandatory output text): ${msgs}`);
  }
  if (base) productLines.push(`User Free-Text Instructions: ${base}`);

  const productBlock = productLines.length > 0 ? productLines.join("\n") : base;

  const referenceInventory = [
    "【参考产品清单 / REFERENCE PRODUCT INVENTORY】",
    "- Treat the active reference image as the factual inventory of the featured product set, not as loose inspiration.",
    allowProductGeometryChange
      ? "- User-requested size/count/lineup changes override the reference only for the specific requested aspect. All non-requested product facts remain locked to the reference."
      : args.type === "detail"
        ? "- For detail close-ups, the reference is authoritative for real local structures and materials. Full-product framing, original subject occupancy, and complete product visibility are NOT required."
      : "- If the user does not explicitly request size/count/lineup changes, keep the same visible product instances, same kit composition, and same relative size relationships as the active reference.",
    isComparison
      ? "- Comparison slides may introduce a separate comparison object, but the featured reference product inventory itself must not be duplicated, reduced, resized, or mutated."
      : args.type === "detail"
        ? "- Do not invent a new macro structure. Crop into a real visible part of the same product, such as an edge, thread, hole, surface texture, seam, interface, blade, groove, connector, fabric weave, packaging finish, or material transition."
      : "- Do not introduce a second copy of any featured product part as a prop, background object, in-use object, or extra accessory unless the user explicitly asks for it.",
    "- If repeated items look identical in the reference, keep them identical in length, scale, and design. Do not turn equal items into a size range or stepped lineup.",
  ].join("\n");

  const providerStrictness = [
    "【编辑模式要求 / EDITING MODE】",
    "- Edit and restage the reference product set; do not redesign it from scratch.",
    "- Because the product reference is the factual source, composition freedom applies to camera, background, lighting, typography, and callout layout only.",
  ].join("\n");

  const visualEnergy = [
    "【视觉张力 / COMMERCIAL VISUAL ENERGY】",
    "- Avoid flat catalog snapshots. Create premium commercial tension through camera angle, lighting contrast, depth, shadows, reflections, material highlights, background layering, and disciplined negative space.",
    "- Visual drama must come from non-product dimensions only: lens choice, perspective, crop, scene depth, surface texture, atmosphere, typography hierarchy, and callout layout.",
    args.type === "detail"
      ? "- For detail close-ups, visual energy may come from a closer camera distance and local crop. This is not a product-size change as long as the enlarged area is a real visible part of the reference product."
      : "- Do NOT create visual energy by changing product count, product size, product proportions, product geometry, or repeated-item length relationships.",
    "- Match the product category rather than forcing an industrial scene: industrial tools can use CNC/workshop/metal textures; pet products can use home/pet interaction context; baby products can use nursery/parenting context; beauty products can use vanity/bathroom/spa surfaces; home goods can use real rooms; electronics can use desk/studio/tech environments; food/kitchen products can use kitchen/tabletop context.",
  ].join("\n");

  const userPromptScope: Record<DetailType, string> = {
    detail:
      "Use the user prompt and heroPlan copy as a copy-material pool for craftsmanship, material, texture, structure, and quality claims. Do not import broad lifestyle or comparison directives into this detail macro slide unless the user explicitly asks.",
    multi_angle:
      "Use the user prompt only for product/category/style hints and the requested viewpoint. Ignore broad scene, background-story, headline, feature-card, comparison, or lifestyle directives that would turn this into a new advertising scene.",
    lifestyle:
      "Use the user prompt's scene/background/use-environment ideas and heroPlan copy as a copy-material pool for application benefits, use-case labels, and concise scene badges. The environment must be category-appropriate and visibly different from the source/reference background. The featured product inventory remains one intact foreground hero set with the same visible count and relative size relationships. Do not duplicate, mutate, or remove featured product components unless explicitly requested.",
    feature:
      "Use the user prompt and heroPlan for selling-point direction, but only call out real visible features. The product image itself is not a design canvas and must not be resized, duplicated, or restructured to fit the layout.",
    comparison:
      "Use the user prompt and heroPlan for the comparison story. Only the comparison counterpart may vary. The featured/ours product must keep the reference inventory, count, relative size, and structure.",
    spec:
      "Use the user prompt and readable reference labels for specs. Annotations explain the reference product; they must not visually alter dimensions, count, or structure.",
  };

  // Hero plan anchors expression and visual consistency; it must not override reference product geometry.
  const styleAnchor = hero
    ? [
        `【主图风格锚定】以下为主图方案的风格与文案参考，商详图必须保持同一视觉体系：`,
        shouldUseHeroCopyDirection ? `- 主标题方向参考（非强制输出文字）：${hero.headline || "（未提供）"}` : "",
        shouldUseHeroCopyDirection && hero.subtitle ? `- 副标题方向参考（非强制输出文字）：${hero.subtitle}` : "",
        shouldUseHeroCopyDirection && hero.sellingPoints && hero.sellingPoints.length > 0
          ? `- 核心卖点池：${hero.sellingPoints.join(" / ")}`
          : "",
        hero.visualDirection ? `- 视觉方向：${hero.visualDirection}` : "",
        hero.colorDirection ? `- 色彩方向：${hero.colorDirection}` : "",
        ``,
        shouldUseHeroCopyDirection
          ? `要求：商详图的光影质感、色调氛围、材质表现必须与主图一致。heroPlan 用于控制产品理解、内容表达方向、卖点方向和视觉体系；其中的标题/文案只是参考方向，不是生成时必须输出的文字；不得覆盖参考图中的产品结构、数量、相对尺寸关系。`
          : `要求：商详图的光影质感、色调氛围、材质表现必须与主图一致。当前功能图不使用 heroPlan 标题/文案作为输出目标；heroPlan 只提供产品理解与视觉风格参考，不得覆盖参考图中的产品结构、数量、相对尺寸关系。`,
      ]
        .filter(Boolean)
        .join("\n")
    : "【未提供主图方案】请根据商品描述自主决定视觉风格，保持商业摄影级质感。";

  const productLock =
    args.type === "detail"
      ? [
          "【局部细节真实性锁 / LOCAL DETAIL FIDELITY LOCK】",
          "- This is a local detail close-up, not a full-product restage. The complete product does NOT need to be visible.",
          "- You may crop tightly into one real visible area of the reference product and enlarge that local area to show material, texture, machining, edge quality, hole/thread detail, interface detail, finish, weave, seam, or surface transition.",
          "- The close-up must still be traceable to the same product. Preserve local geometry, material family, contour logic, hole/thread/edge positions, surface finish, and visible small details.",
          "- Do NOT invent a new component, new hole pattern, new thread pitch, new blade/edge shape, new label, new accessory, or a different product model.",
          "- Full-product apparent size, original subject occupancy, and original framing are intentionally not locked for this detail close-up.",
        ].join("\n")
      : args.type === "lifestyle"
        ? [
            "【场景图产品锁 / LIFESTYLE PRODUCT LOCK】",
            allowProductGeometryChange
              ? "- The user explicitly asked to change product size, scale, dimensions, quantity, or lineup. Apply ONLY that requested product-level change; keep all other product geometry faithful to the references."
              : "- DEFAULT RULE: Preserve the featured product identity, structure, visible count, kit composition, relative size relationships, and apparent foreground scale.",
            "- The scene must change around the product: create a category-appropriate usage environment that is clearly different from the reference/source background.",
            "- Choose the environment from product evidence and user intent. Industrial/workshop scenes are only for industrial tools, machinery, hardware, manufacturing, repair, or construction products; otherwise use the natural category context.",
            "- Show visible scene evidence: relevant surface, room/work area, props, depth, lighting, background texture, and use-context cues. Avoid returning a near-identical background or only changing color grading.",
            "- Keep the featured product as one intact foreground hero set. Do NOT add a second copy, remove pieces, split a kit, mutate geometry, or turn identical parts into a size range unless explicitly requested.",
            "- Category-appropriate hands, tools, furniture, rooms, benches, machines, pets, people, or props may appear as context, but they must not contain a duplicated copy of the featured product or force product geometry changes.",
          ].join("\n")
        : [
            "【产品保真锁 / PRODUCT FIDELITY LOCK】",
            allowProductGeometryChange
              ? "- The user explicitly asked to change product size, scale, dimensions, quantity, or lineup. Apply ONLY that requested product-level change; keep all other product geometry faithful to the references."
              : isComparison
                ? "- DEFAULT RULE: The reference image is authoritative for the FEATURED product's structure, apparent product size/scale, and featured-product instance count. The comparison counterpart may appear because this is a comparison slide, but it must not alter the featured product."
                : "- DEFAULT RULE: The reference image is authoritative for product structure, apparent product size/scale, and product instance count. Do NOT change these unless the user explicitly asks.",
            "- Preserve exact product geometry: outline, proportions, holes, slots, threads, blade edges, grooves, mounting points, chamfers, radii, contours, thickness relationships, and visible small details.",
            allowProductGeometryChange
              ? "- Even when changing the requested dimension/quantity, do not invent unrelated parts, simplify geometry, alter hole count/positions, or transform the product into a different object."
              : isComparison
                ? "- Preserve the featured product count exactly. A generic comparison counterpart is allowed, but do NOT duplicate, resize, or mutate the featured reference product."
                : "- Preserve product count exactly: do NOT add extra copies, variants, accessories, bundles, mirrored duplicates, split duplicate products, or remove any product instance visible in the active reference.",
            allowProductGeometryChange
              ? "- Product scale changes are allowed only where the user requested them; otherwise keep scale relationships consistent with the active reference."
              : "- Preserve apparent product scale and subject occupancy for non-macro slides. The product may be repositioned for layout, but it must not become a different-sized product.",
            allowProductGeometryChange
              ? "- If the user requested a size/count change for a kit or set, apply it consistently to the requested items only."
              : "- For kits/sets/multi-piece products, preserve the exact number of visible pieces and their relative size relationships. Do NOT turn identical items into different-length variants or a size progression.",
            "- Background, typography, callouts, lighting, and scene elements may change for the carousel slide, but they must never require changing the product body.",
          ].join("\n");

  const copyPolicy = !effectiveIncludeMarketingCopy
    ? [
        "【文案策略 / COPY POLICY】",
        includeMarketingCopy
          ? "- This slide does not default to heavy marketing typography. Use no headline/card system by default, but one small functional label is allowed if it improves ecommerce clarity."
          : "- The user explicitly requested no marketing text or text removal. Do not add headline, subtitle, selling-point cards, or decorative copy.",
        "- Product labels physically printed on the product are product appearance, not marketing copy; keep them readable when visible.",
      ].join("\n")
    : preserveExactText
      ? [
          "【文案策略 / COPY POLICY】",
          "- The user explicitly asked to keep the existing text unchanged. Preserve visible headline, subtitle, selling-point copy, and product surface labels as faithfully and readably as possible.",
          "- Do not rewrite, replace, or omit existing readable copy unless it is physically outside the crop.",
        ].join("\n")
      : [
          "【文案策略 / COPY POLICY】",
          "- This is an e-commerce detail slide. The headline must be present and readable; other marketing copy is free-form—use as much or as little as the design naturally needs. Do not make the slide feel textless unless the user explicitly asks for no text.",
          "- Do NOT treat reference-image headline/copy as locked exact text unless the user explicitly asks to keep text unchanged.",
          "- Use heroPlan headline, subtitle, selling points, and copy blocks as the primary copy-material pool. Adapt the wording to fit the current slide type, maintaining a natural balance rather than forcing dense or sparse copy.",
          hero?.headline ? `- Headline direction reference only: "${hero.headline}".` : "",
          hero?.subtitle ? `- Subtitle direction reference only: "${hero.subtitle}".` : "",
          "- Product labels printed on the product itself are part of the product appearance and must remain readable when visible.",
          "- Do not output a textless commercial slide unless the user explicitly asks for no text.",
        ].filter(Boolean).join("\n");

  const common = [
    "You are generating an e-commerce carousel image (product detail page slide).",
    args.type === "detail"
      ? "For this detail close-up, preserve product identity and local structure while allowing tight crop and changed subject occupancy."
      : args.type === "lifestyle"
        ? "For this lifestyle scene, preserve the featured product identity, structure, visible count, relative size relationships, and foreground scale while changing the surrounding category-appropriate environment."
        : isComparison
          ? "Keep the featured product identity, structure, apparent size, and count consistent with the reference image unless the user explicitly requested a product-level change. A separate comparison counterpart may appear for the comparison story."
          : "Keep the product identity, structure, apparent size, and count consistent with the reference image unless the user explicitly requested a product-level change.",
    args.type === "lifestyle"
      ? "Maintain cohesive commercial quality with the hero image, but the surrounding environment must visibly change into a category-appropriate usage scene."
      : args.type === "detail"
        ? "Maintain cohesive commercial quality with the hero image, but move the camera into a real local detail area rather than preserving the original full-product framing."
        : "Maintain the same lighting, color mood, material treatment, and visual atmosphere as the style reference image.",
    "This is a companion image to the main hero image, part of a cohesive product listing set.",
    "Clean commercial look, realistic materials and lighting.",
    "Current provider edit mode uses the active reference image as the actual visual input. Other uploaded images, if any, are only weak contextual memory from the plan/user text, not direct visual evidence.",
    "User free-text instructions are high priority. If the user text assigns semantic roles to images (e.g., dimension image, feature scene image), follow those assignments.",
    "Priority for numeric specs: USER PROMPT explicit values > readable values on uploaded reference images > qualitative non-numeric labels.",
    "If user prompt explicitly provides values/units, copy them exactly as-is. Do not rewrite decimals, units, symbols, or formatting.",
    "If prompt does not provide values but reference image labels include readable values, copy those values exactly.",
    `Visual input used for this edit: active reference image only. Active reference index: ${args.activeReferenceIndex ?? 0}. Uploaded reference count in UI: ${args.referenceImageCount || 1}.`,
    "",
    providerStrictness,
    "",
    referenceInventory,
    "",
    productLock,
    "",
    visualEnergy,
    "",
    "【用户提示词使用边界 / USER PROMPT SCOPE】",
    userPromptScope[args.type],
    "",
    copyPolicy,
    "",
    styleAnchor,
    "",
    "【文案要求】",
    !effectiveIncludeMarketingCopy
      ? includeMarketingCopy
        ? "- 当前功能图默认不输出营销大标题/卖点卡片；如需文字，仅保留产品表面自带标签或用户明确要求的必要短标签。"
        : "- 用户已明确要求无文字/删除文字；不要添加新的营销文案。"
      : preserveExactText
        ? "- 用户明确要求保留原文案时，尽量逐字保留参考图中的可读文案。"
        : "- 默认生成适合当前商详图类型的英文电商文案；heroPlan 文案是主要素材池，可改写但不能把页面做成空文案/弱文案。",
    "- 允许写入用户已提供的信息，以及可从图片稳定判断的非数值信息（如 part type、material family、process style、color family）。",
    "- 禁止虚构无法验证的精确数值或认证信息（例如具体尺寸值、硬度值、证书编号），除非用户明确提供。",
    "- 参数表/标签应尽量填写可用文本，不要把字段大面积留空或只填占位破折号。",
    "- 如有文字，必须清晰可读，不得被产品遮挡。",
  ].join("\n");

  const perType: Record<DetailType, string> = {
    detail: [
      "【功能定位】细节特写图：展示产品工艺、材质纹理、关键结构。",
      "Focus: true local close-up detail shot highlighting craftsmanship, material texture, edges, holes, seams, interfaces, threads, finishes, and key functional surfaces from the reference product.",
      "Composition: use macro / near-macro framing. The full product should usually NOT be visible; crop into one real visible product area and make that local detail the hero.",
      effectiveIncludeMarketingCopy
        ? "Text layout: include 1 concise headline about craftsmanship/material quality plus 2-3 short callout labels pointing to real visible details. Use compact labels or slim callout cards, not an empty beauty shot."
        : "Text layout: avoid marketing headline/card systems. If useful, add only 1-2 tiny technical labels pointing to real visible local details.",
      "Macro means camera distance/crop changes, not product-size redesign. Do NOT redesign the part, change local dimensions, change count, or invent a new close-up structure.",
    ].join("\n"),
    multi_angle: [
      "【功能定位】多角度展示图：从另一视角展示产品整体形体。",
      "Focus: a different camera angle of the exact same product (rotate viewpoint only), showing overall form and structure.",
      "Composition: three-quarter view or side profile with stronger perspective, controlled shadows, premium surface reflections, and clean background. A headline or product name label is recommended; keep supporting text light and unobtrusive.",
      "MANDATORY: Changing viewpoint must NOT change product structure, product dimensions, product count, hole/slot/thread positions, or visible feature count.",
      "If the reference shows a kit with multiple identical bits or parts, all matching items must remain the same length and relative scale. Do NOT create a left-to-right size progression.",
    ].join("\n"),
    lifestyle: [
      "【功能定位】使用场景图：展示产品在真实使用环境中的应用。",
      "Focus: realistic contextual scene that matches the product category and user intent, still commercial and clean. Do not force an industrial scene unless the product/category calls for it.",
      "Composition: show the exact same product set as one intact foreground hero group, with the same visible component count and relative size relationships as the active reference. Use a clearly new category-appropriate environment, background depth, environmental texture, and cinematic lighting to add energy.",
      effectiveIncludeMarketingCopy
        ? "Text layout: include 1 scene/application headline and 2-3 use-case badges or benefit labels integrated into the environment. This slide must look like a designed ecommerce scene page, not only a restaged product photo."
        : "Text layout: prioritize the photographic scene. Avoid marketing headline/card systems; at most use one subtle scene label if it improves clarity.",
      "The scene may include category-appropriate people, pets, babies, rooms, workshops, tools, furniture, outdoor context, kitchen/bathroom/desk surfaces, vehicles, machines, or other relevant environment elements.",
      "Mandatory scene-difference check: the output should not look like the same source image with minor relighting. Add visible new usage-context evidence while preserving the featured product.",
      "Do NOT create an action shot that consumes, separates, duplicates, or mutates one component from the featured product set unless the user explicitly asks for that product-level change.",
      "If the product is industrial/tooling/hardware and the user asks for maintenance/workshop context, use repair activity as environment/context. Any drill, hand, screw, machine, cabinet, or tool in the scene must not contain an extra copy of the featured product.",
    ].join("\n"),
    feature: [
      "【功能定位】卖点爆破图：突出核心卖点，信息层次分明。",
      "Focus: highlight selling points through composition and supporting visual elements.",
      "Composition: same hero product with organized info cards or callout zones, stronger visual hierarchy, confident headline scale, precise pointers, and dimensional spacing. Benefit points should be clearly visualized, not just text.",
      "Text layout: include a strong headline plus 3-5 readable feature blocks derived from heroPlan/user copy/material-visible evidence.",
      "Callouts may point to real visible features only; do NOT add/remove product parts, resize the product body, or duplicate the product.",
    ].join("\n"),
    comparison: [
      "【功能定位】对比优势图：通过对比展示产品优势或升级点。",
      "Focus: product comparison layout, such as ordinary vs upgraded, before/after, or competitor-style comparison. Highlight the featured product's advantage visually.",
      allowProductGeometryChange
        ? "Composition: product-to-product comparison may also reflect the user's requested product size/count/lineup change. The featured product must still preserve all non-requested geometry."
        : "Composition: show the featured reference product against a generic lower-quality / ordinary comparison product of the same category. The comparison object may differ visually to communicate contrast, but it must not be mistaken for the featured product.",
      "Use stronger contrast, side-by-side hierarchy, badges, arrows, split lighting, or benefit rows to make the comparison persuasive; do not make the featured product's size/count/structure the source of contrast.",
      "The featured product side must preserve the reference product exactly in structure, apparent size/scale, and visible features. The comparison counterpart must never cause the featured product to change size, structure, or count.",
    ].join("\n"),
    spec: [
      "【功能定位】规格参数图：展示尺寸、材质、技术参数等关键信息。",
      "Focus: technical specification visualization — dimensions, material, key parameters presented with clarity.",
      "Composition: the same product shown with dimensional callouts, spec labels, or annotated diagram style. Use precise grid rhythm, technical linework, contrast panels, and premium material lighting so the page feels engineered rather than flat.",
      "When exact numeric dimensions are not provided, use qualitative spec text or bounded labels (e.g., 'High Precision', 'Tight Tolerance', 'Custom Size Available') instead of leaving rows blank.",
      "If the user provides exact values, preserve and render them exactly.",
      "Do NOT alter the product dimensions visually to match invented labels. Annotations explain the reference product; they do not redesign it.",
    ].join("\n"),
  };

  return `${common}\n\n${productBlock ? `Product Context:\n${productBlock}\n` : ""}${perType[args.type]}`.trim();
}

async function shouldRetrySpecFill(imageUrl: string): Promise<boolean> {
  try {
    const res = await fetch(LLM_API_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LLM_AUTH_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: LLM_MODEL,
        messages: [
          {
            role: "system",
            content:
              'You are a strict image QA checker. Return JSON only: {"needsRetry": boolean, "reason": string}. needsRetry=true when spec/parameter fields are mostly empty placeholders (e.g., "-", "—", blank).',
          },
          {
            role: "user",
            content: [
              { type: "image_url", image_url: { url: imageUrl } },
              { type: "text", text: "Check if parameter/spec table fields are mostly placeholders or blank. If yes, set needsRetry=true." },
            ],
          },
        ],
        response_format: { type: "json_object" },
        temperature: 0,
        max_tokens: 200,
      }),
    });
    if (!res.ok) return false;
    const data = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
    const content = data?.choices?.[0]?.message?.content;
    if (!content) return false;
    const parsed = JSON.parse(content) as { needsRetry?: boolean };
    return Boolean(parsed.needsRetry);
  } catch {
    return false;
  }
}

function resolveUrl(origin: string, maybeUrl: unknown): string | null {
  if (typeof maybeUrl !== "string") return null;
  const u = maybeUrl.trim();
  if (!u) return null;
  if (u.startsWith("/")) return `${origin}${u}`;
  return u;
}

export async function POST(request: NextRequest) {
  try {
    const scope = await getAuthScope(request);
    if (!scope) {
      return NextResponse.json({ error: "未登录" }, { status: 401 });
    }
    const activeCode = requireActiveAuthorizationCode(scope);
    if (!activeCode.ok) {
      return NextResponse.json({ error: activeCode.error }, { status: activeCode.status });
    }
    const tenantId = "default";

    // 配额检查（将在解析 selectedTypes 后扣除对应数量）
    const quotaCheck = await checkAndResetQuotaForScope(scope);
    if (!quotaCheck.ok) {
      return NextResponse.json(
        { error: quotaErrorMessage(quotaCheck.hoursUntilReset), code: "QUOTA_EXHAUSTED" },
        { status: 429 }
      );
    }

    const body = await request.json();
    const {
      heroImageUrl,
      detailImageUrls,
      activeDetailImageIndex,
      productDescription,
      selectedTypes,
      output,
      heroPlan,
      sessionId,
    } = body as {
      heroImageUrl?: unknown;
      detailImageUrls?: unknown;
      activeDetailImageIndex?: unknown;
      productDescription?: unknown;
      selectedTypes?: unknown;
      output?: { width?: unknown; height?: unknown };
      heroPlan?: unknown;
      sessionId?: unknown;
    };
    const v2SessionId = typeof sessionId === "string" ? sessionId : null;

    const origin = request.nextUrl?.origin || process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
    const resolvedHeroImageUrl = resolveUrl(origin, heroImageUrl);
    if (!resolvedHeroImageUrl) {
      return NextResponse.json({ error: "缺少主图 heroImageUrl" }, { status: 400 });
    }
    const resolvedDetailImageUrls = Array.isArray(detailImageUrls)
      ? detailImageUrls
          .map((u) => resolveUrl(origin, u))
          .filter((u): u is string => Boolean(u))
      : [];
    const currentIndex = Number.isFinite(Number(activeDetailImageIndex)) ? Number(activeDetailImageIndex) : 0;
    const activeRefUrl = resolvedDetailImageUrls[currentIndex] || resolvedHeroImageUrl;
    const referenceUrls = Array.from(new Set([activeRefUrl, ...resolvedDetailImageUrls].filter(Boolean))).slice(0, 6);

    const validTypes: DetailType[] = ["detail", "multi_angle", "lifestyle", "feature", "comparison", "spec"];
    const types: DetailType[] = Array.isArray(selectedTypes)
      ? (selectedTypes.filter((t): t is DetailType => validTypes.includes(t as DetailType)) as DetailType[])
      : [];
    if (types.length === 0) {
      return NextResponse.json({ error: "selectedTypes 不能为空" }, { status: 400 });
    }

    // 检查剩余配额是否足够生成所选类别数量
    if (quotaCheck.remaining < types.length) {
      return NextResponse.json(
        { error: quotaErrorMessage(quotaCheck.hoursUntilReset), code: "QUOTA_EXHAUSTED" },
        { status: 429 }
      );
    }

    const width = Number.isFinite(Number(output?.width)) ? Number(output?.width) : 1024;
    const height = Number.isFinite(Number(output?.height)) ? Number(output?.height) : 1024;

    const providerName = body.provider || process.env.IMAGE_PROVIDER || "chatgpt2api";
    const provider = getImageProvider(providerName);

    const heroContext = extractHeroContext(heroPlan as CreativePlan | null);
    const productLevelChangeAllowed = hasExplicitProductGeometryChangeIntent(
      typeof productDescription === "string" ? productDescription : ""
    );
    const includeMarketingCopy = !hasExplicitTextRemovalIntent(
      typeof productDescription === "string" ? productDescription : ""
    );
    const preserveExactText = hasExplicitExactTextKeepIntent(
      typeof productDescription === "string" ? productDescription : ""
    );

    const pages: Array<{ type: DetailType; imageUrl: string; taskId?: string }> = [];
    let index = 0;
    for (const type of types) {
      const effectiveIncludeMarketingCopy =
        includeMarketingCopy && (preserveExactText || detailTypeDefaultsToMarketingCopy());
      const prompt = buildDetailPrompt({
        type,
        productDescription: typeof productDescription === "string" ? productDescription : "",
        heroContext,
        referenceImageCount: referenceUrls.length,
        activeReferenceIndex: 0,
        allowProductGeometryChange: productLevelChangeAllowed,
        includeMarketingCopy,
        preserveExactText,
      });

      const negativePrompt = buildDetailNegativePrompt(type, productLevelChangeAllowed, effectiveIncludeMarketingCopy);

      const task = await prisma.aiImageTask.create({
        data: {
          tenantId,
          userId: scope.userId,
          authorizationCodeId: scope.authorizationCodeId ?? null,
          promptSnapshot: prompt,
          userPrompt: typeof productDescription === "string" ? productDescription.trim() : null,
          negativePromptSnapshot: negativePrompt,
          configSnapshot: JSON.stringify({ width, height, detailType: type, sessionId: v2SessionId || undefined, strictSize: true, model: "default", quality: "standard", productLevelChangeAllowed, includeMarketingCopy, preserveExactText }),
          referenceImagesSnapshot: JSON.stringify({
            productImageUrl: activeRefUrl,
            styleReferenceUrls: [],
            availableReferenceUrls: referenceUrls,
          }),
          status: "processing",
          provider: providerName,
        },
      });

      const result = await provider.generate({
        prompt,
        negativePrompt,
        productImageUrl: activeRefUrl,
        styleReferenceUrls: [],
        width,
        height,
        strictSize: true,
        editStrength: productLevelChangeAllowed ? 0.65 : 0.35,
        model: "default",
        quality: "standard",
      });

      if (!result.success || !result.imageUrl) {
        await prisma.aiImageTask.update({
          where: { id: task.id },
          data: { status: "failed", errorMessage: result.error || "生成失败" },
        });
        return NextResponse.json({ error: result.error || "生成失败" }, { status: 500 });
      }

      const fileName = `detail-${Date.now()}-${index}.png`;
      let finalImageUrl = result.imageUrl;
      let localUrl = await persistGeneratedImage(finalImageUrl, fileName, origin);
      let effectiveUrl = localUrl || finalImageUrl;

      // Post-check for spec pages: if fields are mostly placeholders, retry once with stricter fill guidance.
      if (type === "spec") {
        const inspectUrl = effectiveUrl.startsWith("/") ? `${origin}${effectiveUrl}` : effectiveUrl;
        const needsRetry = await shouldRetrySpecFill(inspectUrl);
        if (needsRetry) {
          const retryPrompt = `${prompt}

[MANDATORY SPEC FILL RETRY]
- Do not leave spec rows blank or as '-' / '—' unless truly impossible.
- If user prompt contains values, copy exactly as-is (highest priority).
- Else, read values/labels from the active reference image and copy exactly.
- Else, fill with concrete qualitative labels (e.g., "Custom", "By Drawing", "High Precision", "CNC Machined", "Metal Body").
- Ensure most rows are meaningfully filled.`;
          const retry = await provider.generate({
            prompt: retryPrompt,
            negativePrompt,
            productImageUrl: activeRefUrl,
            styleReferenceUrls: [],
            width,
            height,
            strictSize: true,
            editStrength: productLevelChangeAllowed ? 0.65 : 0.35,
            model: "default",
            quality: "standard",
          });
          if (retry.success && retry.imageUrl) {
            finalImageUrl = retry.imageUrl;
            localUrl = await persistGeneratedImage(finalImageUrl, fileName, origin);
            effectiveUrl = localUrl || finalImageUrl;
          }
        }
      }

      await prisma.aiImageTask.update({
        where: { id: task.id },
        data: {
          status: "completed",
          resultImageUrl: JSON.stringify([effectiveUrl]),
        },
      });
      if (v2SessionId) {
        const v2Session = await prisma.aiImageV2Session.findFirst({
          where: { id: v2SessionId, ...scopedTenantUserWhere(scope, tenantId) },
          select: { id: true, userId: true },
        });
        if (v2Session) {
          const existingImage = await prisma.aiImageV2GeneratedImage.findFirst({
            where: { sessionId: v2SessionId, taskId: task.id },
            select: { id: true },
          });
          if (!existingImage) {
            await prisma.aiImageV2GeneratedImage.create({
              data: {
                sessionId: v2SessionId,
                tenantId,
                userId: v2Session.userId,
                taskId: task.id,
                tab: "detail",
                detailType: type,
                imageUrl: effectiveUrl,
              },
            });
            await prisma.aiImageV2Session.update({
              where: { id: v2SessionId },
              data: { updatedAt: new Date() },
            });
          }
        }
      }

      pages.push({ type, imageUrl: effectiveUrl, taskId: task.id });
      index++;
    }

    // 扣除配额（按选择的类别数量）
    const remainingQuota = await deductQuotaForScope(scope, types.length);

    return NextResponse.json({ pages, remainingQuota });
  } catch (error) {
    console.error("[v2/detail/generate] Failed:", error);
    return NextResponse.json({ error: "生成失败" }, { status: 500 });
  }
}
