"use client";

import { useCallback } from "react";
import { toast } from "sonner";
import type { CreativePlan, V2Session } from "../types";
import { buildNoTextImagePrompt } from "../lib/noTextPrompt";
import { resolveImageUrl, nowTs } from "./utils/session-utils";

export interface UseImageGenerationOptions {
  activeSession: V2Session | null;
  updateActiveSession: (updater: (s: V2Session) => V2Session) => void;
  onSessionPersist?: (session: V2Session) => Promise<void> | void;
}

export interface ImageGenerationActions {
  handleGenerateImage: (plan: CreativePlan) => Promise<void>;
}

export function useImageGeneration(options: UseImageGenerationOptions): ImageGenerationActions {
  const { activeSession, updateActiveSession, onSessionPersist } = options;

  const handleGenerateImage = useCallback(
    async (plan: CreativePlan) => {
      const activeProductImage = activeSession?.productImageUrls?.[activeSession?.activeProductImageIndex ?? 0];
      if (!activeProductImage) {
        toast.error("请先上传商品图");
        return;
      }
      updateActiveSession((s) => ({ ...s, generatingImage: true, generatingImagePlanId: plan.id, lastError: null }));

      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 90000);

      try {
        const isChatGPT2API = activeSession.provider === "chatgpt2api";

        const styleRefs = isChatGPT2API
          ? []
          : [
              ...(activeSession.productImageUrls[0] ? [activeSession.productImageUrls[0]] : []),
              ...(activeSession.referenceImageUrls || []),
            ];

        const promptContent =
          plan.finalPrompt || plan.imageGenerationPrompt || buildNoTextImagePrompt(plan);

        const negativePromptBase =
          "watermark, ai generated mark, logo, signature, corner badge, copyright stamp, generated by, ai watermark, brand mark, label, stamp, qr code";

        const res = await fetch("/api/ai-image/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            promptContent,
            productImageUrl: activeProductImage,
            styleReferenceUrls: styleRefs,
            negativePrompt: negativePromptBase,
            provider: activeSession.provider,
            config: {
              width: activeSession.outputWidth,
              height: activeSession.outputHeight,
              model: "default",
              generationModeId: "commercial_showcase",
              editStrength: 0.75,
              strictSize: true,
            },
          }),
          signal: controller.signal,
        });
        clearTimeout(timeoutId);
        const data = await res.json();
        const rawResultImageUrl = data?.data?.resultImageUrl ?? data?.data?.imageUrl ?? data?.imageUrl ?? null;
        const imageUrl = resolveImageUrl(rawResultImageUrl);

        if (res.ok && imageUrl) {
          const rawBase64 = (data?.imageBase64 as string | undefined) || "";
          const imageBase64 =
            rawBase64 && rawBase64.startsWith("data:")
              ? rawBase64
              : rawBase64 && rawBase64.startsWith("http")
                ? ""
                : rawBase64 && rawBase64.length > 64
                  ? `data:image/png;base64,${rawBase64}`
                  : "";
          let nextSession: V2Session | null = null;
          updateActiveSession((s) => ({
            ...(nextSession = {
              ...s,
              generatingImage: false,
              generatingImagePlanId: null,
              generatedImages: [
                {
                  id: globalThis.crypto?.randomUUID?.() || `img-${nowTs()}-${Math.random().toString(36).slice(2, 6)}`,
                  planId: plan.id,
                  taskId: data.data?.id,
                  tab: "product" as const,
                  imageUrl,
                  imageBase64,
                  createdAt: nowTs(),
                },
                ...s.generatedImages,
              ],
            }),
          }));
          if (nextSession) {
            void onSessionPersist?.(nextSession);
          }
          toast.success("图片生成成功");
        } else {
          toast.error(data.error || "生成失败");
          updateActiveSession((s) => ({
            ...s,
            generatingImage: false,
            generatingImagePlanId: null,
            lastError: data.error || "生成失败",
          }));
        }
      } catch (err: unknown) {
        clearTimeout(timeoutId);
        if (err instanceof Error && err.name === "AbortError") {
          toast.error("生成超时（90秒），请重试");
          updateActiveSession((s) => ({
            ...s,
            generatingImage: false,
            generatingImagePlanId: null,
            lastError: "生成超时（90秒）",
          }));
        } else {
          toast.error("网络错误，请重试");
          updateActiveSession((s) => ({
            ...s,
            generatingImage: false,
            generatingImagePlanId: null,
            lastError: "网络错误",
          }));
        }
      }
    },
    [activeSession, onSessionPersist, updateActiveSession]
  );

  return { handleGenerateImage };
}
