"use client";

import { useCallback } from "react";
import { toast } from "sonner";
import type { CreativePlan, V2Session } from "../types";
import { buildNoTextImagePrompt, isLimitedScope } from "../lib/noTextPrompt";
import { refreshPlanPrompts } from "@/lib/plan/refresh";
import { resolveImageUrl, nowTs } from "./utils/session-utils";

export interface UseImageGenerationOptions {
  activeSession: V2Session | null;
  updateActiveSession: (updater: (s: V2Session) => V2Session) => void;
  onSessionPersist?: (session: V2Session) => Promise<void> | void;
}

export interface ImageGenerationResult {
  success: boolean;
  imageUrl?: string;
  imageBase64?: string;
  error?: string;
  taskId?: string;
}

export interface ImageGenerationActions {
  handleGenerateImage: (plan: CreativePlan) => Promise<ImageGenerationResult>;
}

export function useImageGeneration(options: UseImageGenerationOptions): ImageGenerationActions {
  const { activeSession, updateActiveSession, onSessionPersist } = options;

  const handleGenerateImage = useCallback(
    async (rawPlan: CreativePlan): Promise<ImageGenerationResult> => {
      const plan = refreshPlanPrompts(rawPlan);
      const activeProductImage = activeSession?.productImageUrls?.[activeSession?.activeProductImageIndex ?? 0];
      if (!activeProductImage) {
        toast.error("请先上传商品图");
        return { success: false, error: "请先上传商品图" };
      }
      updateActiveSession((s) => ({ ...s, generatingImage: true, generatingImagePlanId: plan.id, lastError: null }));

      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 150000);

      try {
        const isChatGPT2API = activeSession.provider === "chatgpt2api";

        const styleRefs = isChatGPT2API
          ? []
          : [
              ...(activeSession.productImageUrls[0] ? [activeSession.productImageUrls[0]] : []),
              ...(activeSession.referenceImageUrls || []),
            ];

        const userGoal = activeSession?.goal || "";
        const limitedScope = isLimitedScope(userGoal);
        const promptContent = limitedScope
          ? buildNoTextImagePrompt(plan, userGoal)
          : (plan.finalPrompt || plan.imageGenerationPrompt || buildNoTextImagePrompt(plan, userGoal));

        const negativePromptBase =
          "watermark, ai generated mark, logo, signature, corner badge, copyright stamp, generated by, ai watermark, brand mark, label, stamp, qr code";

        const res = await fetch("/api/ai-image/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            sessionId: activeSession.id,
            planId: plan.id,
            promptContent,
            productImageUrls: activeSession.productImageUrls,
            styleReferenceUrls: styleRefs,
            negativePrompt: negativePromptBase,
            provider: activeSession.provider,
            config: {
              width: activeSession.outputWidth,
              height: activeSession.outputHeight,
              model: "default",
              generationModeId: "commercial_showcase",
              editStrength: 0.75,
              strictSize: true,
            },
          }),
          signal: controller.signal,
        });
        clearTimeout(timeoutId);
        const data = await res.json();
        const rawResultImageUrl = data?.data?.resultImageUrl ?? data?.data?.imageUrl ?? data?.imageUrl ?? null;
        const imageUrl = resolveImageUrl(rawResultImageUrl);
        const thumbUrl = data?.thumbUrl as string | undefined;

        if (res.ok && imageUrl) {
          const rawBase64 = (data?.imageBase64 as string | undefined) || "";
          const imageBase64 =
            rawBase64 && rawBase64.startsWith("data:")
              ? rawBase64
              : rawBase64 && !rawBase64.startsWith("http") && rawBase64.length > 0
                ? `data:image/png;base64,${rawBase64}`
                : "";
          const taskId = data.data?.id as string | undefined;
          let nextSession: V2Session | null = null;
          updateActiveSession((s) => ({
            ...(nextSession = {
              ...s,
              generatingImage: false,
              generatingImagePlanId: null,
              generatedImages: [
                {
                  id: globalThis.crypto?.randomUUID?.() || `img-${nowTs()}-${Math.random().toString(36).slice(2, 6)}`,
                  planId: plan.id,
                  taskId,
                  tab: "product" as const,
                  imageUrl,
                  thumbUrl,
                  imageBase64,
                  createdAt: nowTs(),
                },
                ...s.generatedImages,
              ],
            }),
          }));
          if (nextSession) {
            void onSessionPersist?.(nextSession);
          }

          // 后台持久化外部图片到本地，避免后续加载慢或 URL 失效
          if (taskId && imageUrl && !imageUrl.startsWith("/") && !imageUrl.startsWith("data:")) {
            fetch(`/api/ai-image/tasks/${taskId}/persist-image`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ imageUrl }),
            })
              .then(async (persistRes) => {
                if (!persistRes.ok) return;
                const persistData = (await persistRes.json()) as { localUrl?: string; thumbUrl?: string };
                if (!persistData.localUrl) return;
                updateActiveSession((s) => {
                  const next = {
                    ...s,
                    generatedImages: s.generatedImages.map((g) =>
                      g.taskId === taskId
                        ? { ...g, imageUrl: persistData.localUrl as string, thumbUrl: persistData.thumbUrl || g.thumbUrl }
                        : g
                    ),
                  };
                  void onSessionPersist?.(next);
                  return next;
                });
              })
              .catch(() => {
                /* 忽略后台错误 */
              });
          }

          toast.success("图片生成成功");
          return { success: true, imageUrl, imageBase64, taskId };
        } else {
          const errorMsg = (res.status === 429 && data.code === "QUOTA_EXHAUSTED")
            ? (data.error || "配额已耗尽")
            : (data.error || "生成失败");
          toast.error(errorMsg);
          updateActiveSession((s) => ({
            ...s,
            generatingImage: false,
            generatingImagePlanId: null,
            lastError: errorMsg,
          }));
          return { success: false, error: errorMsg };
        }
      } catch (err: unknown) {
        clearTimeout(timeoutId);
        if (err instanceof Error && err.name === "AbortError") {
          const errorMsg = "生成超时（90秒），请重试";
          toast.error(errorMsg);
          updateActiveSession((s) => ({
            ...s,
            generatingImage: false,
            generatingImagePlanId: null,
            lastError: errorMsg,
          }));
          return { success: false, error: errorMsg };
        } else {
          const errorMsg = "网络错误，请重试";
          toast.error(errorMsg);
          updateActiveSession((s) => ({
            ...s,
            generatingImage: false,
            generatingImagePlanId: null,
            lastError: errorMsg,
          }));
          return { success: false, error: errorMsg };
        }
      }
    },
    [activeSession, onSessionPersist, updateActiveSession]
  );

  return { handleGenerateImage };
}
